# 网站基础信息
baseURL = "/"  # GitHub Pages 地址
languageCode = "zh-CN"
title = "wangx"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "zh"

# 分页（新写法）
[pagination]
  pagerSize = 10   # 每页文章数量


# 多语言支持
[languages]
  [languages.zh]
    languageName = "中文"
    weight = 1

# 菜单设置
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 3

[params]
  description = "wangx，分享技术与生活。"
  showReadingTime = true
  dateFormat = "2006-01-02"
  showToc = true
  enableEmoji = true
  ShowCodeCopyButtons = true     # 开启代码块右上角复制按钮
  tocPosition = "right"    # 目录显示在右侧
  tocOpen = true           # 默认展开目录
  assets = { favicon = "favicon.png"}
  mainSections = []


[markup]
  [markup.highlight]
    noClasses = false            # 用 CSS 控制高亮（推荐）
    abchotLineNos = true
    codeFences = true            # 启用代码块
    guessSyntax = true           # 自动猜测语言
    lineNos = true              # 是否显示行号（可改成 true）
    style = "github"             # 使用 GitHub 风格的语法高亮